-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg1OVfqFOKwk8bZ1f7
S7tIOHyZp1FI3hIXmIweor/I1dGgCgYIKoZIzj0DAQehRANCAASptXFEiCwWfk7T
m1Vv+jcrEwQ7EaxbzxCALosHuOQTReJRLKhf+V04h5alwge0t1no1yeAKB1E7qGJ
kyGCeutu
-----END PRIVATE KEY-----